### ISSUE TITLE
Images are still editable with readOnly=true

### ISSUE THREAD

**Issue by johannchen** [globocom/megadraft#82] opened 2016-10-17 16:17 UTC
picture is still in editable mode even when the prop readOnly is set to true. Also the size adjustment dropdown for picture does nothing.

**Comment by ricobl** [comment] 2016-10-18 00:08
Hey @johannchen, I think you're right about the `readOnly` property, thanks for pointing that out, I'll change the issue title to better reflect this ok?

About the dropdown... it just changes the `display` property of the image block, but not the editor appearance. One could save this data and use this option to change how the image is displayed on the actual website or application.

**Comment by macrozone** [comment] 2016-10-19 13:18
on readOnly, the sidebar is also still visible

**Comment by Tbutnyakov** [comment] 2016-12-27 15:34
Hello!
There are some news on this issue?

**Comment by wdtamagi** [comment] 2019-10-14 14:21
I will work on this.  ;)

**Comment by wdtamagi** [comment] 2019-10-15 18:18
@marcelometal

**Comment by JeanPinzon** [comment] 2019-10-16 18:56
This should be fixed by https://github.com/globocom/megadraft/commit/8db42aebb15b2712970856162b6c91709b1f772a

**Comment by osmarpetry** [comment] 2019-10-17 00:25
@johannchen can you reproduce this error in https://codesandbox.io/ or https://stackblitz.com/?

**Comment by wdtamagi** [comment] 2019-10-17 12:15
@johannchen I believe this issue has been closed by my PR.

**Comment by wdtamagi** [comment] 2019-10-19 13:50
@JeanPinzon @marcelometal 
I submmited a new PR (https://github.com/globocom/megadraft/pull/262) to fix a bug caused by my other PR.

**Comment by JeanPinzon** [comment] 2019-10-23 21:13
This should be fixed by https://github.com/globocom/megadraft/commit/f0a2c0b0b38bd515c6e361b9ead6cc244e455711

**Closed by JeanPinzon** 2019-10-23 21:13 UTC
Labels: bug, good first issue, hacktoberfest, help wanted
